from typing import Protocol

from app.ledger.model import Entry


class LedgerStore(Protocol):
    def ensure_account(self, account_id: str) -> None: ...

    def balance(self, account_id: str) -> int: ...

    def append(self, entry: Entry) -> None: ...

    def entries(self, account_id: str) -> list[Entry]: ...

    def find_by_idempotency(self, account_id: str, idempotency_key: str) -> Entry | None: ...

    def get(self, entry_id: str) -> Entry | None: ...
